### ISSUE TITLE
I hope to support the nebulogunityclientsample and the 2020 version. There is  error in newtonsoft JSON

### ISSUE THREAD

**Issue by LikeScientist** [imadyTech/NebuLog#15]
Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included or the current platform. Only one assembly with the same name is allowed per platform. (Assets/Plugins/SignalR/Newtonsoft.Json.dll)
----------------------------------------------------------------------------Deleted after↓↓↓
(Filename: Library/PackageCache/com.unity.ide.visualstudio@2.0.11/Editor/VisualStudioIntegration.cs Line: 149)

CachePath: C:/Users/Administrator/AppData/LocalLow/Unity/imady_NebuLogUnitySample
CachePath: C:/Users/Administrator/AppData/LocalLow/Unity/imady_NebuLogUnitySample
Reloading assemblies for play mode.
Begin MonoManager ReloadAssembly
Assembly 'Library/ScriptAssemblies/Assembly-CSharp.dll' will not be loaded due to errors:
Reference has errors 'Microsoft.AspNetCore.SignalR.Protocols.Json'.

Assembly 'Assets/Plugins/SignalR/Microsoft.AspNetCore.Http.Connections.Common.dll' will not be loaded due to errors:
Microsoft.AspNetCore.Http.Connections.Common references strong named Newtonsoft.Json Assembly references: 11.0.0.0 Found in project: 12.0.0.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"

Assembly 'Assets/Plugins/SignalR/Microsoft.AspNetCore.Http.Connections.Client.dll' will not be loaded due to errors:
Reference has errors 'Microsoft.AspNetCore.Http.Connections.Common'.

Assembly 'Assets/Plugins/SignalR/Microsoft.AspNetCore.SignalR.Client.Core.dll' will not be loaded due to errors:
Reference has errors 'Microsoft.AspNetCore.SignalR.Common'.

Assembly 'Assets/Plugins/SignalR/Microsoft.AspNetCore.SignalR.Client.dll' will not be loaded due to errors:
Reference has errors 'Microsoft.AspNetCore.SignalR.Client.Core'.

Assembly 'Assets/Plugins/SignalR/Microsoft.AspNetCore.SignalR.Common.dll' will not be loaded due to errors:
Microsoft.AspNetCore.SignalR.Common references strong named Newtonsoft.Json Assembly references: 11.0.0.0 Found in project: 12.0.0.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"

Assembly 'Assets/Plugins/SignalR/Microsoft.AspNetCore.SignalR.Protocols.Json.dll' will not be loaded due to errors:
Microsoft.AspNetCore.SignalR.Protocols.Json references strong named Newtonsoft.Json Assembly references: 11.0.0.0 Found in project: 12.0.0.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"

**Comment by imadyTech** [comment]
Hi,
I tried to open NebulogUnityClientSample with Unity 2020.3.6 and it worked well.
It seems that you have 2 Newtonsoft.Json.dll in your unity project folder for some reason, and therefore had all the subsequent error reports. You may search the "Newtonsoft.Json.dll" with file Explorer and delete the redundant one (other than the DLL under Assets/Plugins).
Another possible solution is you may start a new unity project, and then copy the contents under the NebuLogUnityClientSample/Assets folder to the same directory in your new project. I think that works.
Unity has poor supports to the .NET Core libraries (actually unity only officially supports .Net Framework 4) and it spent me quite a while to find out the workable version of SignalR libraries (I have included all the dlls to Github). 
Keep in mind that Nebulog is not a ready-2-publish opensource project but only a sample to demonstrate how to intercept the Unity log messages and distribute via SignalR, therefore I was not able to have it well maintained recently. However I will be glad to support if anything I can do. Please let me know if you managed to have it run, or not.
Good luck!

**Comment by LikeScientist** [comment]
If you are a Chinese, maybe we use Chinese to communicate, the translation is too tired.

**Comment by LikeScientist** [comment]
我换在2019.4.13f1c1的unity上运行NebuLogUnityClientSample，但是NebuLogServerSample的任何一个程序都接收不到unity的log，我在知乎看你的文章过来的，我想知道是否还有其他修改的地方或者设置，或许你可以在youtube或者b站上传个使用方法

**Comment by imadyTech** [comment]
如果是server收不到消息，那可能是你机器上的IP地址设置不对。
我看了一下server program.cs里面地址是：

                    .UseUrls("http://*:5999")

所以如果你本机跑server和client的话，client上应该设置为127.0.0.1:5999或者localhost:5999。
    public class UnityNebulogger :IUnityNebulog, IDisposable
    {
        .....
#if DEVELOPMENT_DEBUG
        public static string defaulNebulogHubUri = "http://192.168.0.20/NebuLogHub";
#else
        //public static string defaulNebulogHubUri = "https://nebulog.yingyu88.cn/NebuLogHub";
#endif
这个地址你改成localhost。
如果还不行，你可以加我QQ 352862120，我发完整的项目zip给你。










在2022年04月22 ***@***.***>写道：


我换在2019.4.13f1c1的unity上运行NebuLogUnityClientSample，但是NebuLogServerSample的任何一个程序都接收不到unity的log，我在知乎看你的文章过来的，我想知道是否还有其他修改的地方或者设置，或许你可以在youtube或者b站上传个使用方法

**Comment by LikeScientist** [comment]
我先加下你QQ，Maybe我应该先Try跑起来，这两天就Beigin Try





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "imadyTech/NebuLog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月23日(星期六) 上午9:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [imadyTech/NebuLog] I hope to support the nebulogunityclientsample and the 2020 version. There is  error in newtonsoft JSON (Issue #15)





 
 如果是server收不到消息，那可能是你机器上的IP地址设置不对。
 我看了一下server program.cs里面地址是：
 
                     .UseUrls("http://*:5999")
 
 所以如果你本机跑server和client的话，client上应该设置为127.0.0.1:5999或者localhost:5999。
     public class UnityNebulogger :IUnityNebulog, IDisposable
     {
         .....
 #if DEVELOPMENT_DEBUG
         public static string defaulNebulogHubUri = "http://192.168.0.20/NebuLogHub";
 #else
         //public static string defaulNebulogHubUri = "https://nebulog.yingyu88.cn/NebuLogHub";
 #endif
 这个地址你改成localhost。
 如果还不行，你可以加我QQ 352862120，我发完整的项目zip给你。
 
 
 
 
 
 
 
 
 
 
 在2022年04月22 ***@***.***&gt;写道：
 
 
 我换在2019.4.13f1c1的unity上运行NebuLogUnityClientSample，但是NebuLogServerSample的任何一个程序都接收不到unity的log，我在知乎看你的文章过来的，我想知道是否还有其他修改的地方或者设置，或许你可以在youtube或者b站上传个使用方法
