### ISSUE TITLE
确定是分布式日志?

### ISSUE THREAD

**Issue by xiaolu6t** [imadyTech/NebuLog#3]
为什么没有记录项目名称?
如果我有5个项目,如何确定异常来自哪个项目?

**Comment by imadyTech** [comment]
日志信息源项目的appsetting里面可以设置项目信息。在日志管理端对应“Project”栏目。
使用方法更新到知乎博客了，可以参考https://www.zhihu.com/column/c_1290065947668226048。
嗯，至于分布式日志，只是相对于本地日志而言，最初写nebulog时候心也大了点。本项目只是对.net core日志体系/signalr传输做了次初级的探究，并非成熟的体系，只是提供一个实现的思路。目前我也没有时间、没有能力、没有动力去完善这个项目。对于实际项目建议还是找合适的成熟开源或者商业性的框架来实现日志功能。
